<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23" started-at="2019-04-30T09:35:28Z" finished-at="2019-04-30T09:35:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23" started-at="2019-04-30T09:35:28Z" finished-at="2019-04-30T09:35:28Z">
      <class name="Tests.LoginTest">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:Tests.LoginTest@6d8a00e3]" name="setUp" is-config="true" duration-ms="0" started-at="2019-04-30T15:05:28Z" finished-at="2019-04-30T15:05:28Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.ef.qa.base.TestBase.initialization(TestBase.java:33)
	at Tests.LoginTest.setUp(LoginTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="validateLoginPageTitleTest()[pri:0, instance:Tests.LoginTest@6d8a00e3]" name="validateLoginPageTitleTest" duration-ms="1" started-at="2019-04-30T15:05:28Z" finished-at="2019-04-30T15:05:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginPageTitleTest -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:Tests.LoginTest@6d8a00e3]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-04-30T15:05:28Z" finished-at="2019-04-30T15:05:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
